---
title: "Intro to R Class 2 Practice"
author: "Maura Oray - GDI Boston"
date: "10/23/2018"
output: html_document
---

```{r setup, include=FALSE}
#Load libraries here

library(ggplot2)
library(data.table)

```


```{r}

#Set your working directory

setwd("~/Desktop/GDI")

```


```{r}

#Load the dataset and name the data frame

iris <- read.csv("Iris.csv")


```

```{r}

#Explore the data set (hint: check descriptive statistics and data types)

summary(iris)
str(iris)

```

```{r}

#Remove first column of the data set

iris <- iris[-c(1)]

```


```{r}

#Rename columns 1,2,3,4: Sepal_Length, Sepal_Width, Petal_Length, Petal_Width

names(iris) <- c("Sepal_Length", "Sepal_Width", "Petal_Length", "Petal_Width", "Species")

#Another way

"Sepal_Length" <- colnames(iris)[colnames(iris)=="SepalLengthCm"]

#Yet Another Way

setnames(iris, old=c("SepalLengthCm", "SepalWidthCm"), new=c("Sepal_Length", "Sepal_Width"))

```

```{r}

#Change Species to character and then view 

iris$Species <- as.character(iris$Species)

summary(iris$Species)

#Change Species back to factor and view

iris$Species <- as.factor(iris$Species)

summary(iris$Species)
  
```  
```{r}

#Create a simple histogram of Sepal Width (and change title and labels)

hist(iris$Sepal_Width,
     xlab = "Sepal Width", 
     main = "Sepal Width Distribution")

```

```{r}

#Create a ggplot histogram of Sepal Width (and change title and labels)

ggplot(data=iris, aes(x=Sepal_Width)) +
  geom_histogram(binwidth = 0.2, aes(fill=Species)) +
  xlab("Sepal Width") + 
  ylab("Frequency") +
  ggtitle("Sepal Width Distribution")

```

```{r}

#Create ggplot boxplot of Species and Petal Length

ggplot(data=iris, aes(x=Species, y=Petal_Length, fill=Species)) +
  geom_boxplot() +
  xlab("Species") + 
  ylab("Petal Length") +
  ggtitle("Boxplot of Petal Length and Species") +
  theme(legend.position = "none")

```
```{r}

#Create a density plot of Sepal Length and fill with Species

ggplot(data=iris, aes(x=Sepal_Length, fill=Species)) +
  geom_density(alpha=0.3) +
  xlab("Sepal Length (cm)") + 
  ylab("Density") +
  ggtitle("Density Plot of Sepal Length") +
  theme(legend.position = "none")

```

```{r}

#Create a scatterplot of Petal Length v. Petal Width
#CHALLENGE: Add a regession line (hint use geom_smooth())

ggplot(data=iris, aes(x=Petal_Length, y = Petal_Width)) +
  geom_point(aes(color=Species, shape=Species)) +
  geom_smooth(method="lm") +
  xlab("Petal Length (cm)") + 
  ylab("Petal Width (cm)") +
  ggtitle("Petal Length v. Petal Width")

```

```{r}

#Scatterplot of Sepal Length v. Sepal Width

ggplot(data=iris, aes(x=Sepal_Length, y=Sepal_Width)) +
  geom_point(aes(color=Species, shape=Species)) +
  xlab("Sepal Length (cm)") + 
  ylab("Sepal Width (cm)") +
  ggtitle("Sepal Length v. Sepal Width") 

```
